app/Project/urls.py
"""URL Configuration """

# Django
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path('', include(('loans.urls', 'loans'), namespace='loans')),
    path('', include(('users.urls', 'users'), namespace='users')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/loans/urls.py
# Django
from django.urls import path

# Rest
from rest_framework import routers

# ViewSets
from .views import LoanListViewSet, GenderViewSet, LoanViewSet
from . import views

# Router Rest
router = routers.SimpleRouter()
router.register(r'genders', GenderViewSet, basename='genders')
router.register('nuevo_prestamo', LoanViewSet, basename='nuevoPrestamo')
router.register('lista_prestamos', LoanListViewSet, basename='listaPrestamo')

urlpatterns = [
    path('new_loan/', views.nuevo_prestamo, name='new_loan'),
    path('list_loans/', views.lista_prestamos, name='list_loans'),
    path('home/', views.home, name='home'),
]
urlpatterns += router.urls

app/users/urls.py
"""Users URLs."""

# Django
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

# Django REST Framework
from rest_framework.routers import DefaultRouter

# Views
from .views import UserViewSet

router = DefaultRouter()
router.register(r'users', UserViewSet, basename='users')


urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html', redirect_authenticated_user=True), name='login'),

    path('logout/', LogoutView.as_view(next_page='loans:home'), name='logout'),

]
urlpatterns += router.urls

app/loans/models.py
"""Loan Model"""
# Utils

import requests

# Django
from django.db import models
from django.conf import settings

# Utils
from utils.models import BaseModel

STATUS_WAITING = 0
STATUS_ACCEPTED = 1
STATUS_REJECTED = 2
STATUS_ERROR = 3

STATUS_CHOICES = (
    (STATUS_WAITING, 'En espera'),
    (STATUS_ACCEPTED, 'Aceptado'),
    (STATUS_REJECTED, 'Rechazado'),
    (STATUS_ERROR, 'Error'),
)


class Gender(BaseModel):
    """Gender Model"""

    name = models.CharField(max_length=20)
    slug_name = models.SlugField()

    def __str__(self):
        return self.slug_name


class Loan(models.Model):
    """Loan Model"""

    dni = models.IntegerField()
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.ForeignKey(Gender, on_delete=models.CASCADE)
    email = models.EmailField()
    monto = models.FloatField()
    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=STATUS_WAITING
    )

    def prescore(self):
        url = '{}{}'.format(settings.URL_LOAD, self.dni)
        header = {
            'credential': settings.CREDENTIAL
        }
        request = requests.get(url, headers=header)
        response = request.json()
        if response['has_error']:
            self.status = STATUS_ERROR
        elif response['status'] == 'approve':
            self.status = STATUS_ACCEPTED
        else:
            self.status = STATUS_REJECTED
        self.save()

    def get_status_name(self):
        return STATUS_CHOICES[self.status]

app/users/models.py
""" User model."""

# Django
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy

# Utilities
from utils.models import BaseModel


class User(BaseModel, AbstractUser):
    """ User model.Extend from Django's Abstract User, change the username field
    to email"""

    email = models.EmailField(
        'email',
        unique=True,
        error_messages={
            'unique': ugettext_lazy('Ya existe un usuario con este email')
        }
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    def __str__(self):
        return self.username

app/utils/models.py
"""Django models utilities"""

# Django
from django.db import models


class BaseModel(models.Model):
    """
    BaseModel acts as an abstract base class from wich every
    other model in the project will inherit. This class provides
    every table with the following attributes:
        + created (DateTime): Store the datetime the object was created.
        + modified (Datetime): Store the las datetime the object was modified.
    """

    created = models.DateTimeField(
        'created at',
        auto_now_add=True,
        help_text='Date time on which the object was created.'
    )
    modified = models.DateTimeField(
        'modified at',
        auto_now=True,
        help_text='Date time on which the object was modified.'
    )

    class Meta:
        """ Meta option. """
        abstract = True
        get_latest_by = 'created'
        ordering = ['-created', '-modified', ]

app/loans/views.py
"""Loan views."""

# Django Rest Framework
from rest_framework import viewsets, mixins
from rest_framework.decorators import api_view
from rest_framework.response import Response

# Permissions
from rest_framework.permissions import IsAuthenticated, AllowAny

# Models
from .models import Loan, Gender

# Serializers
from .serializers import LoanSerializer, GenderSerializer

# Django
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def lista_prestamos(request):
    return render(request, 'loans/list_loans.html')


def nuevo_prestamo(request):
    return render(request, 'loans/new_loans.html')


def home(request):
    return render(request, 'home.html')


class LoanListViewSet(viewsets.ModelViewSet):
    """Loan List view set"""
    queryset = Loan.objects.all()
    serializer_class = LoanSerializer
    search_fields = ('dni', 'first_name', 'last_name', 'email')
    filterset_fields = ('status', 'gender')

    def get_permissions(self):
        permissions = []
        if self.action in ['update', 'partial_update', 'list', 'delete']:
            permissions.append(IsAuthenticated)
        if self.action == 'create':
            permissions.append(AllowAny)
        else:
            permissions.append(IsAuthenticated)
        return [permission() for permission in permissions]


class GenderViewSet(mixins.ListModelMixin,
                    viewsets.GenericViewSet):
    """Gender view set"""
    queryset = Gender.objects.all()
    serializer_class = GenderSerializer

    def get_permissions(self):
        permissions = [AllowAny]
        return [permission() for permission in permissions]


class LoanViewSet(viewsets.ModelViewSet):
    """Loan view set"""
    serializer_class = LoanSerializer
    queryset = Loan.objects.all()

app/users/views.py
"""Users views."""

# Django REST Framework
from rest_framework import mixins, status, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

# Permissions
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated
)
from .permissions import IsAccountOwner

# Serializers
from .serializer import (
    UserLoginSerializer,
    UserModelSerializer,
    UserSignUpSerializer
)

# Models
from .models import User


class UserViewSet(mixins.RetrieveModelMixin,
                  mixins.UpdateModelMixin,
                  viewsets.GenericViewSet):

    """User view set.
    Sign up and login
    """
    queryset = User.objects.filter(is_active=True)
    serializer_class = UserModelSerializer
    lookup_field = 'username'

    def get_permissions(self):
        if self.action in ['signup', 'login', 'verify']:
            permissions = [AllowAny]
        elif self.action in ['retrieve']:
            permissions = [IsAuthenticated, IsAccountOwner]
        else:
            permissions = [IsAuthenticated]
        return [p() for p in permissions]

    @action(detail=False, methods=['post'])
    def login(self, request):
        serializer = UserLoginSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()
        data = {
            'user': UserModelSerializer(user).data
        }
        return Response(data, status=status.HTTP_201_CREATED)

    @action(detail=False, methods=['post'])
    def signup(self, request):
        serializer = UserSignUpSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()
        data = UserModelSerializer(user).data
        return Response(data, status=status.HTTP_201_CREATED)

    def retrieve(self, request, *args, **kwargs):
        response = super(UserViewSet, self).retrieve(request, *args, **kwargs)
        data = {
            'user': response.data,
        }
        response.data = data
        return response

app/templates/base.html
{%load static%}
<!DOCTYPE html>
	<head>
	<meta charset="utf-8">
	<!-- Bootstrap  -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-home.css'%}">
	</head>

	<body>
	{%block body%}

        {%block content%}
        {%endblock%}

	{%endblock%}
	<!-- Bootstrap  -->
	<script src="{% static 'js/bootstrap.min.js'%}"></script>
	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js'%}"></script>
	<!-- jCookie -->
	<script type="module" src="{% static 'js/js.cookie.mjs'%}"></script>
    {%block javascript%}
    {%endblock%}
	</body>
</html>

app/templates/home.html
{% extends 'base.html'%}
{%load static%}



<title>Prestamos Moni</title>
<meta name="viewport" content="width=device-width, initial-scale=1">

{%block body%}

{%block content%}
<div class="w3-top">
  <div class="w3-bar w3-white w3-wide w3-padding w3-card">
    <a href="#home" class="w3-bar-item w3-button"><b>Moni</b> Prestamos Online</a>

    <div class="w3-right w3-hide-small">
      <a href="{% url 'loans:list_loans' %}" class="w3-bar-item w3-button">Listado de Prestamos</a>
      <a href="{% url 'loans:new_loan' %}" class="w3-bar-item w3-button">Solicitar un Prestamo</a>
      <a href="#about" class="w3-bar-item w3-button">Sobre Nosotros</a>
      <a href="{% url 'users:login' %}" class="w3-bar-item w3-button">Iniciar Sesion</a>
    </div>
  </div>
</div>

<!-- Header -->
<header class="w3-display-container w3-content w3-wide" style="max-width:1500px;" id="home">
  <img class="w3-image" src="{% static 'img/moni.png' %}" alt="Moni" width="1500" height="800">
  <div class="w3-display-middle w3-margin-top w3-center">
    <h1 class="w3-xxlarge w3-text-white"><span class="w3-padding w3-black w3-opacity-min"><b>Moni</b></span> <span class="w3-hide-small w3-text-light-grey">Prestamos Online</span></h1>
  </div>
</header>

<!-- Page content -->
<div class="w3-content w3-padding" style="max-width:1564px">


  <!-- About Section -->
  <div class="w3-container w3-padding-32" id="about">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Sobre Nosotros</h3>
    <p>Hola! Soy Moni, tu billetera incondicional. <br>
    <p>Baja la app de Moni 
        Bajá la App <span><a href="https://play.google.com/store/apps/details?id=com.moni.android&hl=es_AR" title="MoniApp" target="_blank" class="w3-hover-text-green"> haciendo click AQUI</a></span>, completá tus datos y listo… simplificá tu vida!<br>
        💵 Pedime un préstamo de hasta $30.000 en 6 cuotas<br>
        📄 Pagá los servicios con o sin factura<br>
        📲 Recargá el celu<br>
        🚌 Cargá la SUBE<br>
        💳 Comprá con MoniCard<br>
        El préstamo es 100% online y se te acredita al instante. Para devolverme es muy fácil ya que podés usar cualquiera de los medios habilitados: Saldo de tu Billetera Moni, Tarjeta de débito, Transferencia o depósito a mi cuenta bancaria o Código de barra en Rapipago, Pago fácil u otra agencia de cobro.
        Realizá tus pagos y recargas desde el celu, sin hacer filas y en el momento que quieras. Lo podés pagar con tu tarjeta de débito, con tu Billetera Moni o con un Préstamo.
        Pedí GRATIS tu MoniCard. Vas a poder suscribirte a Netflix y Spotify, hacer compras online y también en comercios adheridos a Mastercard. Aprovechá nuestros descuentos! Cargala con tu tarjeta de débito o con un préstamo. Así, comprás ahora y me devolvés más adelante y en cuotas.
        Moni #TeLoHagoMásSimple
    </p>
  </div>

</div>


<!-- Footer -->
<footer class="w3-center w3-black w3-padding-16">
  <h3>Visita nuestras redes sociales!</h3>


  <img src="{% static 'img/instagram.png' %}" width="50" height="50" />
  <p>Nuestro <a href="https://www.instagram.com/monibilletera/" title="Instagram" target="_blank" class="w3-hover-text-green">Instagram</a></p>

  <img src="{% static 'img/facebook.png' %}" width="50" height="50" />
  <p>Nuestra pagina de <a href="https://www.facebook.com/Moniprestamos/" title="Facebook" target="_blank" class="w3-hover-text-green">Facebook</a></p>

  <img src="{% static 'img/youtube.png' %}" width="50" height="50" />
  <p>Nuestro canal de <a href="https://www.youtube.com/channel/UCsnRxGaS96r67W1V5OvCDGQ" title="Youtube" target="_blank" class="w3-hover-text-green">Youtube</a></p>
  
</footer>

{%endblock%}


{%endblock%}

app/templates/loans/list_loans.html
{% extends 'base.html'%}
{%load static%}


{%block content%}

<div class="w3-top">
    <div class="w3-bar w3-white w3-wide w3-padding w3-card">
      <a href="{% url 'loans:home' %}" class="w3-bar-item w3-button"><b>Moni</b> Prestamos Online</a>
  
      <div class="w3-right w3-hide-small">              
        <a href="{% url 'loans:new_loan' %}" class="w3-bar-item w3-button">Solicitar un Prestamo</a>
      </div>
    </div>
</div>            


<header class="w3-display-container w3-content w3-wide" style="max-width:1500px;" id="home">
    <img class="w3-image" src="{% static 'img/moni.png' %}" alt="Moni" width="1500" height="800">
    <div class="w3-display-middle w3-margin-top w3-center">
        <h1 class="w3-xxlarge w3-text-white"><span class="w3-padding w3-black w3-opacity-min"><b>Moni</b></span> <span class="w3-hide-small w3-text-light-grey">Lista de Prestamos</span></h1>
    </div>
</header>

<div class="row row-bottom-padded-md loan-form">
    <div class="col-md-12">
        <h1>Lista de Prestamos</h1>
        <table class="table list-filled">
            <thead>
                <tr>
                    <th>Cliente</th>
                    <th>Email</th>
                    <th>Préstamo</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>

    </div>
</div>

<template id="row-loan">
    <tr class="text-row row-loan">
        <td>
            <p class="no-margins"><span class="first-name"></span> <span class="last-name"></span></p>
            <p class="no-margins text-row-secondary">DNI <span class="dni"></span></p>
            <p class="no margins gender text-row-secondary"></p>
        </td>
        <td>
            <a href="" target="__blank" class="email"></a>
        </td>
        <td>
            <p class="no-margins">$<span class="amount"></span></p>
            <p class="no-margins text-row-secondary"><span class="status"></span></p>
        </td>
        <td>

            <button class="btn btn-danger btn-delete">Eliminar</button>
        </td>
    </tr>
</template>


{%endblock%}

{%block javascript%}    

    <script src="{% static 'js/list_genders.js'%}"
        id="list-genders-script"
        data-url-genders="{%url 'loans:genders-list' %}">
    </script>


    <script src="{% static 'js/list_loan.js'%}"
        id="list-loan-script"
        data-csrftoken="{{ csrf_token }}"
        data-url-loan="{%url 'loans:listaPrestamo-list' %}">
    </script>

{%endblock%}

app/templates/loans/new_loans.html
{% extends 'base.html'%}
{%load static%}

{%block content%}

    <div class="w3-top">
        <div class="w3-bar w3-white w3-wide w3-padding w3-card">
          <a href="{% url 'loans:home' %}" class="w3-bar-item w3-button"><b>Moni</b> Prestamos Online</a>
      
          <div class="w3-right w3-hide-small">              
            <a href="{% url 'loans:list_loans' %}" class="w3-bar-item w3-button">Listado de Prestamos</a>
            <a href="{% url 'users:login' %}" class="w3-bar-item w3-button">Iniciar Sesion</a>
          </div>
        </div>
    </div>            


    <header class="w3-display-container w3-content w3-wide" style="max-width:1500px;" id="home">
        <img class="w3-image" src="{% static 'img/moni.png' %}" alt="Moni" width="1500" height="800">
        <div class="w3-display-middle w3-margin-top w3-center">
            <h1 class="w3-xxlarge w3-text-white"><span class="w3-padding w3-black w3-opacity-min"><b>Moni</b></span> <span class="w3-hide-small w3-text-light-grey">Solicitud de Prestamo</span></h1>
        </div>
    </header>

    <div class="w3-content w3-padding" style="max-width:1564px">
        <div class="row row-bottom-padded-md loan-form">
            <h1>Solicitud de Prestamo</h1>
            <form id="form"> 
                <div class="form-group">
                    <label for="first_name_id" class="ho">Nombre</label>
                    <input id="first_name_id" name="first_name" class="form-control rounded" placeholder="Nombre" type="text" required>
                </div>
                <div class="form-group">
                    <label for="last_name_id" class="ho">Apellido</label>
                    <input id="last_name_id" name="last_name" class="form-control" placeholder="Apellido" type="text" required>
                </div>
                <div class="form-group">
                    <label for="email_id" class="ho">Email</label>
                    <input id="email_id" name="email" class="form-control" placeholder="Email" type="email" required>
                </div>
                <div class="form-group">
                    <label for="dni_id" class="ho">DNI</label>
                    <input id="dni_id" name="dni" class="form-control" placeholder="DNI" type="number" min=1000000 max=100000000 required>
                </div>
                <div class="form-group">
                    <label for="gender_id" class="ho">Sexo</label>
                    <select name="gender" id="gender_id" class="form-control"></select>
                </div>
                <div class="form-group">
                    <label for="amount_id" class="ho">Monto</label>
                    <input id="amount_id" name="amount" placeholder="Monto" class="form-control" type="number" min=1 max=80000 required>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary btn-lg btn-loan" id="ocultar" type="button">Solicitar Prestamo</button>
                </div> 
                <p class="text-danger text-bold error"></p>
            </form>   
        </div>
    </div>    
    
            <div id='cargando'>
                <h2 align="center"> Se esta evaluando el pedido...</h2>
            </div>

            <div id='aceptado'>
                <br>          
                <h2 align="center"> Su pedido ha sido aprobado, nos comunicaremos por mail para indicarle los pasos a seguir</h2>         
                <p align="center"><a href="{% url 'loans:home' %}" title="Volver" class="w3-hover-text-green"> Volver al inicio</a>
            </div>

            <div id='rechazado'>
                <br> 
                <h2 align="center"> El pedido ha sido rechazado, usted no cumple con las condiciones necesarias para adquirir el prestamo</h2>       
            <p align="center"><a href="{% url 'loans:new_loan' %}" title="Volver"class="w3-hover-text-green"> Solicitar otro prestamo</a>

            </div>  
            
            <div id='err'>
                <br> 
                <h2 align="center"> Ha ocurrido un error, intenta nuevamente</h2>      
            <p align="center"><a href="{% url 'loans:new_loan' %}" title="Volver" class="w3-hover-text-green"> Solicitar otro prestamo</a>
            </div> 
 
{%endblock%}

{%block javascript%}

    <script src="{% static 'js/list_genders.js'%}"
        id="list-genders-script"
        data-url-genders="{%url 'loans:genders-list' %}">
    </script>
  
    <script src="{% static 'js/new_loan.js'%}"
        id="new-loan-script"
        data-csrftoken="{{ csrf_token }}"
        data-url-loan="{%url 'loans:nuevoPrestamo-list' %}"
        data-url-genders="{%url 'loans:genders-list' %}">
    </script>
{%endblock%}

app/templates/users/login.html
{% extends 'base.html'%}

{%load static%}  

{%block content%}

    <div class="w3-top">
        <div class="w3-bar w3-white w3-wide w3-padding w3-card">
            <a href="{% url 'loans:home' %}" class="w3-bar-item w3-button"><b>Moni</b> Prestamos Online</a>

            <div class="w3-right w3-hide-small">              
                <a href="{% url 'loans:list_loans' %}" class="w3-bar-item w3-button">Listado de Prestamos</a>
                <a href="{% url 'loans:new_loan' %}" class="w3-bar-item w3-button">Solicitar un Prestamo</a>
            </div>
        </div>
    </div>    

    <header class="w3-display-container w3-content w3-wide" style="max-width:1500px;" id="home">
        <img class="w3-image" src="{% static 'img/moni.png' %}" alt="Moni" width="1500" height="800">
        <div class="w3-display-middle w3-margin-top w3-center">
        <h1 class="w3-xxlarge w3-text-white"><span class="w3-padding w3-black w3-opacity-min"><b>Moni</b></span> <span class="w3-hide-small w3-text-light-grey">Iniciar Sesion</span></h1>
        </div>
    </header>

<div class="row row-bottom-padded-md loan-form">
    <div class="col-md-6 col-md-offset-3">
                
        <h1>Iniciar Sesión</h1>
        <form id="form" method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{%url 'loans:home'%}">

            <div class="form-group ">
                <label for="username_id">Email</label>
                <input id="username_id" name="username" class="form-control rounded" placeholder="Email" type="email" required>
            </div>
            <div class="form-group ">
                <label for="password_id">Contraseña</label>
                <input id="password_id" name="password" class="form-control" placeholder="Contraseña" type="password" required>
            </div>
            <p class="text-danger text-bold error"></p>
            <div class="form-group ">
                <button class="btn btn-primary btn-lg">Iniciar Sesión</button>
            </div>
            <p class="text-danger">{{form.errors}}</p>
        </form>
    </div>
</div>

<!-- Footer -->
<footer class="w3-center w3-black w3-padding-16">
    <h3>Visita nuestras redes sociales!</h3>
  
  
    <img src="{% static 'img/instagram.png' %}" width="50" height="50" />
    <p>Nuestro <a href="https://www.instagram.com/monibilletera/" title="Instagram" target="_blank" class="w3-hover-text-green">Instagram</a></p>
  
    <img src="{% static 'img/facebook.png' %}" width="50" height="50" />
    <p>Nuestra pagina de <a href="https://www.facebook.com/Moniprestamos/" title="Facebook" target="_blank" class="w3-hover-text-green">Facebook</a></p>
  
    <img src="{% static 'img/youtube.png' %}" width="50" height="50" />
    <p>Nuestro canal de <a href="https://www.youtube.com/channel/UCsnRxGaS96r67W1V5OvCDGQ" title="Youtube" target="_blank" class="w3-hover-text-green">Youtube</a></p>
    
  </footer>
{%endblock%}	